name: Authenticate to Conjur

on:
  push:
    branches:
      - main  # Trigger this workflow on pushes to the main branch

jobs:
  authenticate:
    runs-on: ubuntu-latest  # Use Ubuntu runner

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2  # Checkout code

    - name: Install curl
      run: |
        sudo apt-get update
        sudo apt-get install -y curl  # Install curl for API calls

    - name: Authenticate to Conjur and Get Token
      id: authenticate
      run: |
        # Print the API Key (for debugging) to ensure it's being passed correctly (only for debugging, not recommended in production)
        echo "Using API Key: ${{ secrets.CONJUR_API_KEY }}"
        
        # Run the curl command with verbose output for debugging
        response=$(curl --silent --header "Accept-Encoding: base64" \
          --data "${{ secrets.CONJUR_API_KEY }}" \
          --write-out "%{http_code}" \
          --output response.txt \
          https://sme-andrew.secretsmgr.cyberark.cloud/api/authn/conjur/host%2Fdata%2Feyatest1/authenticate)

        # Debugging: Print the response and HTTP status code
        echo "Response: $(cat response.txt)"
        echo "HTTP Status Code: $response"

        # Check if token is received and save to environment variable
        if [ -n "$(cat response.txt)" ]; then
          echo "auth_token=$(cat response.txt)" >> $GITHUB_ENV
        else
          echo "Failed to authenticate. No token received."
          exit 1
        fi

    - name: Display the Authentication Token
      run: |
        echo "Successfully authenticated. Token: ${{ env.auth_token }}"
