name: Authenticate to Conjur

on:
  push:
    branches:
      - main  # Trigger this workflow on pushes to the main branch

jobs:
  authenticate:
    runs-on: ubuntu-latest  # Use Ubuntu runner

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2  # Checkout code

    - name: Install curl
      run: |
        sudo apt-get update
        sudo apt-get install -y curl  # Install curl for API calls

    - name: Authenticate to Conjur and Get Token
      id: authenticate
      run: |
        # Run the curl command and print the full response
        response=$(curl --header "Accept-Encoding: base64" \
          --data "${{ secrets.CONJUR_API_KEY }}" \
          https://sme-andrew.secretsmgr.cyberark.cloud/api/authn/conjur/host%2Fdata%2Feyatest1/authenticate)

        # Debugging: Print the response to see if we're getting the expected token
        echo "Response: $response"

        # Capture the token if the response is not empty
        if [ -n "$response" ]; then
          echo "auth_token=$response" >> $GITHUB_ENV
        else
          echo "Failed to authenticate. No token received."
          exit 1
        fi

    - name: Display the Authentication Token
      run: |
        echo "Successfully authenticated. Token: ${{ env.auth_token }}"
