name: Authenticate to Conjur

on:
  push:
    branches:
      - main  # Trigger this workflow on pushes to the main branch

jobs:
  authenticate:
    runs-on: ubuntu-latest  # Use Ubuntu runner

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2  # Checkout code

    - name: Install curl
      run: |
        sudo apt-get update
        sudo apt-get install -y curl  # Install curl for API calls

    - name: Authenticate to Conjur and Get Token
      id: authenticate
      run: |
        # Run the curl command to authenticate with Conjur and get the token
        auth_token=$(curl --header "Accept-Encoding: base64" \
          --data "${{ secrets.CONJUR_API_KEY }}" \
          https://sme-andrew.secretsmgr.cyberark.cloud/api/authn/conjur/host%2Fdata%2Feyatest1/authenticate)

        # Save the auth_token to an environment variable for later steps
        echo "auth_token=$auth_token" >> $GITHUB_ENV

    - name: Display the Authentication Token
      run: |
        echo "Successfully authenticated. Token: ${{ env.auth_token }}"
